disabled_rules:
  - trailing_whitespace
  - force_cast
  - force_try

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicit_return
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

included:
  - ExploreGame

excluded:
  - Carthage
  - Pods
  - build
  - .build

line_length:
  warning: 120
  error: 150

identifier_name:
  min_length: 1
  max_length: 60

type_name:
  min_length: 3
  max_length: 40

function_parameter_count:
  warning: 6
  error: 8

large_tuple:
  warning: 3
  error: 4

cyclomatic_complexity:
  warning: 10
  error: 20

file_length:
  warning: 400
  error: 500

type_body_length:
  warning: 200
  error: 300

function_body_length:
  warning: 50
  error: 100